### ISSUE TITLE
动态数据怎么渲染呢

### ISSUE THREAD

**Issue by wzbooks** [iamobj/vue-big-wheel#2]
定义好的静态数据可以显示，请问动态数据要怎么处理呢

**Comment by wzbooks** [comment]
想了个办法解决了。
**需要在组件初始化前获取数据，不能用异步请求**
在router的beforeEach方法中，请求数据，存到localStorage中
`localStorage.setItem("listData", JSON.stringify(listData))`
在转盘抽奖页面的created方法中接收
`this.listData = JSON.parse(localStorage.getItem("listData"))`

**Comment by iamobj** [comment]
后面我再开放个重新渲染的api吧，奖品数量更改后，再重新调下重新渲染的api，最近太忙了，公司下半年的需求都排满了，苦逼996中....:grin:
