### ISSUE TITLE
3q

### ISSUE THREAD

**Issue by YaFeng1844173476** [iamobj/vue-big-wheel#4]
作者很棒，文档很详细，但是如果文字下面要加小图标那怎么办呀

**Comment by iamobj** [comment]
非常抱歉，目前不支持加奖品图片功能，奖品只能文字，得等有时间，我再重构下这个组件，把这个需求加上去，你如果急用，不用等我了，我都不知道，我要啥时候才能有时间，接手了一个重构项目，每天苦逼加班中。。。
