### ISSUE TITLE
大转盘挺棒的，大转盘还可以可以加图片吗。。。

### ISSUE THREAD

**Issue by YaFeng1844173476** [iamobj/vue-big-wheel#5]

**Comment by iamobj** [comment]
目前不可以，正在计划重构中，到时候会加入这个功能，还有一些其它的优化；因为年底，要忙公司项目进度，这个只能保证重构版本在春节之前会发布:joy:

**Comment by YaFeng1844173476** [comment]
谢谢大佬，太忙了邮件才记得回
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ruan HongChao"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月23日(星期六) 上午9:00
收件人： &nbsp;“ iamobj / vue-big-wheel” <vue-big-wheel@noreply.github.com&gt;;
抄送： &nbsp;“ dt” <1844173476@qq.com&gt;;“作者” <author@noreply.github.com&gt;;
主题:&nbsp;Re: [iamobj/vue-big-wheel] 大转盘挺棒的，大转盘还可以可以加图片吗。。。 (#5)




目前不可以，正在计划重构中，到时候会加入这个功能，还有一些其它的优化；因为年底，要忙公司项目进度，这个只能保证重构版本在春节之前会发布😂
  
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。
